INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('000000');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('000080');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('00008B');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('0000CD');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('0000FF');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('006400');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('008000');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('008080');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('008B8B');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('00BFFF');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('00CED1');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('00FA9A');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('00FF00');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('00FF7F');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('00FFFF');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('00FFFF');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('191970');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('1E90FF');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('20B2AA');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('228B22');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('2E8B57');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('2F4F4F');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('32CD32');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('3CB371');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('40E0D0');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('4169E1');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('4682B4');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('483D8B');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('48D1CC');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('4B0082');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('556B2F');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('5F9EA0');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('6495ED');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('66CDAA');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('696969');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('6A5ACD');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('6B8E23');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('708090');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('778899');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('7B68EE');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('7CFC00');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('7FFF00');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('7FFFD4');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('800000');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('800080');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('808000');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('808080');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('87CEEB');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('87CEFA');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('8A2BE2');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('8B0000');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('8B008B');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('8B4513');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('8FBC8F');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('90EE90');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('9370DB');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('9400D3');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('98FB98');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('9932CC');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('9ACD32');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('A0522D');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('A52A2A');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('A9A9A9');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('ADD8E6');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('ADFF2F');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('AFEEEE');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('B0C4DE');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('B0E0E6');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('B22222');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('B8860B');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('BA55D3');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('BC8F8F');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('BDB76B');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('C0C0C0');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('C71585');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('CD5C5C');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('CD853F');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('D2691E');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('D2B48C');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('D3D3D3');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('D8BFD8');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('DA70D6');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('DAA520');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('DB7093');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('DC143C');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('DCDCDC');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('DDA0DD');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('DEB887');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('E0FFFF');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('E6E6FA');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('E9967A');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('EE82EE');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('EEE8AA');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('F08080');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('F0E68C');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('F0F8FF');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('F0FFF0');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('F0FFFF');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('F4A460');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('F5DEB3');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('F5F5DC');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('F5F5F5');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('F5FFFA');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('F8F8FF');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FA8072');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FAEBD7');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FAF0E6');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FAFAD2');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FDF5E6');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FF0000');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FF00FF');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FF00FF');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FF1493');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FF4500');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FF6347');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FF69B4');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FF7F50');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FF8C00');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFA07A');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFA500');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFB6C1');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFC0CB');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFD700');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFDAB9');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFDEAD');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFE4B5');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFE4C4');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFE4E1');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFEBCD');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFEFD5');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFF0F5');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFF5EE');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFF8DC');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFFACD');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFFAF0');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFFAFA');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFFF00');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFFFE0');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFFFF0');
INSERT INTO `ctrlp`.`UserColors` (`Color`) VALUES ('FFFFFF');

CALL add_user('user01','user01@email.com','asd123','asd123');
CALL add_user('user02','user02@email.com','asd123','asd123');

INSERT INTO `ctrlp`.`ModelCategories` (`category_title`) VALUES ('3D Printing');
INSERT INTO `ctrlp`.`ModelCategories` (`category_title`) VALUES ('Art');
INSERT INTO `ctrlp`.`ModelCategories` (`category_title`) VALUES ('Fashion');
INSERT INTO `ctrlp`.`ModelCategories` (`category_title`) VALUES ('Gadgets');
INSERT INTO `ctrlp`.`ModelCategories` (`category_title`) VALUES ('Hobby');
INSERT INTO `ctrlp`.`ModelCategories` (`category_title`) VALUES ('Household');
INSERT INTO `ctrlp`.`ModelCategories` (`category_title`) VALUES ('Learning');
INSERT INTO `ctrlp`.`ModelCategories` (`category_title`) VALUES ('Models');
INSERT INTO `ctrlp`.`ModelCategories` (`category_title`) VALUES ('Tools');
INSERT INTO `ctrlp`.`ModelCategories` (`category_title`) VALUES ('Toys & Games');

INSERT INTO `ctrlp`.`Models` (`Users_idUsers`, `ModelCategories_idModelCategories`, `model_title`, `upload_date`, `model_description`, `model_views`) VALUES ('1', '2', 'Fan Mount', '2014-02-01 10:10:10', 'Something', '0');
INSERT INTO `ctrlp`.`Models` (`Users_idUsers`, `ModelCategories_idModelCategories`, `model_title`, `upload_date`, `model_description`, `model_views`) VALUES ('1', '2', 'Extruder', '2014-02-01 10:10:11', 'Something else', '0');
INSERT INTO `ctrlp`.`Models` (`Users_idUsers`, `ModelCategories_idModelCategories`, `model_title`, `upload_date`, `model_description`, `model_views`) VALUES ('2', '3', 'Thing', '2014-02-01 10:10:12', 'Something', '0');

INSERT INTO `ctrlp`.`Downloads` (`Users_idUsers`, `Models_idModels`, `download_date`) VALUES ('1', '1', '2014-03-01 10:10:10');
INSERT INTO `ctrlp`.`Downloads` (`Users_idUsers`, `Models_idModels`, `download_date`) VALUES ('2', '1', '2014-03-01 10:10:11');
INSERT INTO `ctrlp`.`Downloads` (`Users_idUsers`, `Models_idModels`, `download_date`) VALUES ('1', '2', '2014-03-01 10:10:12');
INSERT INTO `ctrlp`.`Downloads` (`Users_idUsers`, `Models_idModels`, `download_date`) VALUES ('2', '3', '2014-03-01 10:10:13');

INSERT INTO `ctrlp`.`ModelPictures` (`Models_idModels`, `picture_location`, `picture_title`, `picture_comment`, `upload_date`, `main_photo`) VALUES ('1', '/place/place', 'Something01', 'something01', '2014-02-01 10:11:10', '1');
INSERT INTO `ctrlp`.`ModelPictures` (`Models_idModels`, `picture_location`, `picture_title`, `picture_comment`, `upload_date`) VALUES ('1', '/place/place2', 'Something02', 'something02', '2014-02-01 10:11:11');
INSERT INTO `ctrlp`.`ModelPictures` (`Models_idModels`, `picture_location`, `picture_title`, `picture_comment`, `upload_date`, `main_photo`) VALUES ('2', '/place2/place', 'Something03', 'something03', '2014-02-01 10:11:12', '1');
INSERT INTO `ctrlp`.`ModelPictures` (`Models_idModels`, `picture_location`, `picture_title`, `picture_comment`, `upload_date`, `main_photo`) VALUES ('3', '/place3/place', 'Something04', 'something04', '2014-02-01 10:11:13', '1');
